### ISSUE TITLE
Please increase version support for the Openwrt system platform in wireguard-over-wss.

### ISSUE THREAD

**Issue by l-g-t** [jnsgruk/wireguard-over-wss#12]
Please increase version support for the Openwrt system platform in wireguard-over-wss.

**Comment by jnsgruk** [comment]
Hey! There isn't anything in here that would prevent running on OpenWRT, you just need to make sure you grab the release of `wstunnel` that suits your acrchitecture, and write a short init script to start it on boot if that's something you need (see: https://openwrt.org/docs/techref/initscripts).
