### ISSUE TITLE
Config for windows

### ISSUE THREAD

**Issue by drippy8-D** [jnsgruk/wireguard-over-wss#13]
I'm new to networking and I need to make a home vpn but I have a windows client. Can you please make a Config for windows or atleast help me by someway by sharing some links. I really need somebody's help but there's very less information on this topic.

**Comment by jnsgruk** [comment]
Hi, I don't really have any plans to port this to Windows. Another user did put together a script to help with this, which might be useful to you - but it didn't come with any docs, and I haven't tested it myself: https://github.com/jnsgruk/wireguard-over-wss/pull/10/files
