### ISSUE TITLE
nobody user must have execution permission for /usr/loca/bin/wstunnel

### ISSUE THREAD

**Issue by Ali-Flt** [jnsgruk/wireguard-over-wss#2]
since you're running `/usr/loca/bin/wstunnel` with `user=nobody` on the client in your script, you should mention that `nobody` has to have execution permission.

I suggest adding this to the readme:
```
sudo chmod 705 /usr/local/bin/wstunnel
```

**Comment by jnsgruk** [comment]
Thanks for the report, I've added a section to the docs that makes this more obvious.
