### ISSUE TITLE
ERROR: /etc/wireguard/wstunnel.sh: line 119: dig: command not found

### ISSUE THREAD

**Issue by pahlse** [jnsgruk/wireguard-over-wss#5]
```
ERROR: /etc/wireguard/wstunnel.sh: line 119: dig: command not found
```
 I get the above error when I run `$ sudo wg-quick up myvpn` on my archlinux machine. Any ideas what's going wrong?

**Comment by svpi11** [comment]
It seems that you haven't the dig command installed ? Maybe try a "apt install dig" ?

**Comment by jnsgruk** [comment]
Indeed, you need to install `dig` from your distribution. On Ubuntu you can do that with `sudo apt install dnsutils`, but it depends on your distro.
