### ISSUE TITLE
unexpected argument '-v' found

### ISSUE THREAD

**Issue by redsmokelinux** [jnsgruk/wireguard-over-wss#8]
**

> /etc/systemd/system/wstunnel.service

**
This line is not working
**ExecStart=/usr/local/bin/wstunnel -v --server wss://0.0.0.0:443 --restrictTo=127.0.0.1:51820**

> **Error**

> systemctl status wstunnel.service

wstunnel.service - Tunnel WG UDP over websocket
     Loaded: loaded (/etc/systemd/system/wstunnel.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-12-20 18:27:14 UTC; 6s ago
    Process: 942 ExecStart=/usr/local/bin/wstunnel -v --server wss://0.0.0.0:443 --restrictTo=127.0.0.1:51820 (code=exited, status=2)
   Main PID: 942 (code=exited, status=2)
        CPU: 1ms

Dec 20 18:27:14 wireguard-vpn systemd[1]: Started Tunnel WG UDP over websocket.
Dec 20 18:27:14 wireguard-vpn wstunnel[942]: error: unexpected argument '-v' found
Dec 20 18:27:14 wireguard-vpn wstunnel[942]: Usage: wstunnel <COMMAND>
Dec 20 18:27:14 wireguard-vpn wstunnel[942]: For more information, try '--help'.
Dec 20 18:27:14 wireguard-vpn systemd[1]: wstunnel.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 20 18:27:14 wireguard-vpn systemd[1]: wstunnel.service: Failed with result 'exit-code'.

**Comment by jnsgruk** [comment]
Hey, sorry for the delay here!

What happened here is that `wstunnel` transitioned to a new major version which changed the CLI arguments required. You can use the old code if you download `wstunnel < 9`, but I've also updated the instructions and scripts in two recent commits to make it work with `wstunnel >= 9`, which you're welcome to test out too!
